# Generated by Django 4.2.5 on 2023-09-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileing',
            field=models.ImageField(default='C:\\Users\\WellDone\\Desktop\\social_book\\static\\assets\\images\\avatars\\avatar-7.jpg', upload_to='profile_images'),
        ),
    ]
