# Generated by Django 4.2.5 on 2023-09-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='followers',
            new_name='follower',
        ),
    ]
